FROM apache/airflow:3.1.6-python3.11 AS base-setup

USER root
RUN apt-get update && apt-get install -y build-essential libpq-dev git
USER airflow
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM base-setup AS production
COPY --chown=airflow:root . /opt/airflow/project
RUN pip install --no-cache-dir /opt/airflow/project
ENV PYTHONPATH="/opt/airflow/project/src"