services:
  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prefect-worker
    restart: always
    env_file:
      - .env
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_API_KEY=${PREFECT_API_KEY}
    volumes:
      - .:/app
